### ISSUE TITLE
Use hassio secrets

### ISSUE THREAD

**Issue by mgriffin13** [quentinsf/rollease-acmeda#1]
If you broke down the MQTT url into piece parts, then you wouldn't need to hard-code your mqtt password. You could do something like this

```
{
  "mqtt": {
    "host": "192.168.0.31",
    "user": "hassio-mqtt",
    "pass": "!secret mqtt_password",
    "topic": "homeassistant",
  },
  "device": "/dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_018DF044-if00-port0"
}
```

**Comment by quentinsf** [comment]
Yes, that would be nice, wouldn't it?  I don't think the `!secret` in add-on configs is directly supported, though, so I'd need to write a bit of a hack.  I may get around to it at some point...

Do let me know if you you're aware of an easy way of doing this, though!

**Comment by mgriffin13** [comment]
I'm not 100% sure, but it looks like if you look at other examples, like the glances add-on, they use bashio and it might do the conversion for you. Take a look at https://github.com/hassio-addons/addon-glances/blob/master/glances/rootfs/etc/cont-init.d/glances.sh#L32

**Comment by quentinsf** [comment]
Mmm, yes.   Though interestingly, when I had a quick browse of the bashio source, I notice that a recent commit had a log entry along the lines of ‘Remove secrets support, since it’s now supported by Hassio directly’.  Let me see...  [here](https://github.com/hassio-addons/bashio/pull/14).

So I might not need to do anything except split it up into bits.  You might even find it works right now if you put the whole URL into the secret?... I’m afraid I can’t easily try it at present...

**Comment by mgriffin13** [comment]
I'm still trying to get my rollease hub to work over the RS485 port, but that's another issue. I can take a look to see if the whole URL would work.
