### ISSUE TITLE
Subscription to Devices stops at 15

### ISSUE THREAD

**Issue by AdamCavaliere** [quentinsf/rollease-acmeda#2]
I have 17 shades, and the subscription for MQTT events / devices seems to stop at 15, even though it is showing in the logs that there are 17 devices, as it reports back on position status in the logs. 

I have looked through the source code, and it doesn't look like it should be stopping at 15 devices, as it is a for loop. Any idea why the subscription is stopping at 15?

**Comment by quentinsf** [comment]
Hi Adam,
Sorry, no, I don't have any immediate suggestions.  I ended up switching to other people's network-based code instead of the RS485, and then a v2 Pulse hub, and I'm now using a Bond Bridge Pro instead of any Rollease hardware at all, so I'm afraid it's a long time since I looked at this code!
I see that the 'hbmqtt' library on which this was based has also not been maintained for a long time, so it might be worth [switching to the new fork](https://github.com/njouanin/hbmqtt/issues/235).
I have only about 12 blinds, and I don't have the serial cables etc any more, so I'm afraid I probably can't easily help.  If you're using this code and would like to update it, though, I'm happy to incorporate changes or add you as a contributor!
All the best, 
Quentin
